# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-16 12:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_in_school', models.CharField(choices=[(b'FR', b'Freshman'), (b'SO', b'Sophomore'), (b'JR', b'Junior'), (b'SR', b'Senior')], max_length=2)),
                ('age', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('courses', models.ManyToManyField(blank=True, null=True, to='core.Course')),
            ],
            options={
                'es_mapping': {'properties': {'age': {'type': 'short'}, 'course_names': {'index': 'not_analyzed', 'store': 'yes', 'type': 'string'}, 'first_name': {'index': 'not_analyzed', 'type': 'string'}, 'last_name': {'index': 'not_analyzed', 'type': 'string'}, 'name_complete': {'analyzer': 'simple', 'max_input_length': 50, 'payloads': True, 'preserve_position_increments': True, 'preserve_separators': True, 'type': 'completion'}, 'university': {'properties': {'name': {'index': 'not_analyzed', 'type': 'string'}}, 'type': 'object'}, 'year_in_school': {'type': 'string'}}},
                'es_index_name': 'django',
                'es_type_name': 'student',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.University'),
        ),
    ]
